### ISSUE TITLE
Fix insecure images from Imgur

### ISSUE THREAD

**Issue by MrAdder** [IFDevelopment/BeamExtended#18]
Fix Insecure images from Imgur and serve them over HTTPS

**Comment by Exuviax** [comment]
This should already be done, we use a proxy for them over HTTPS from Plugcubed

**Comment by MrAdder** [comment]
Its not still causes insecure images


On 19 March 2015 at 01:43, Exuviax <notifications@github.com> wrote:

> This should already be done, we use a proxy for them over HTTPS from
> Plugcubed
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ExuDev/BeamExtended/issues/18#issuecomment-83255698>.
>



-- 
This email and any files transmitted with it are confidential and contain
privileged or copyright information. It is intended solely for the
individual(s) to whom it is addressed. You must not present this message to
another party without gaining permission from the sender. If you are not
the intended recipient you must not copy, distribute or use this email or
the information contained in it for any purpose other than to notify us.

If you have received this message in error, please notify the sender
immediately, and delete this email from your system. We do not guarantee
that this material is free from viruses or any other defects although due
care has been taken to minimise the risk.
