### ISSUE TITLE
Premium user icon is overriding Mod icon.

### ISSUE THREAD

**Issue by SephirothWS** [IFDevelopment/BeamExtended#39]
Just as the title says, I've got the premium user icon, but I'm mod in this channel in the screenshot.

http://i.imgur.com/DTowVo0.png

**Comment by MrAdder** [comment]
Fixed as of [This Commit](https://github.com/IFDevelopment/BeamExtended/commit/83b5b04650f7b38cbdb10d139d4049c00ecd92a7)
