### ISSUE TITLE
User tooltip is blank if no special ranks.

### ISSUE THREAD

**Issue by SephirothWS** [IFDevelopment/BeamExtended#40]
http://i.imgur.com/h18Hzxm.png

There's two things I'd like to see on this.

1. Remove the tooltip completely if it's going to be blank.
2. Add in an option for users to use to put back in the "user" part in the tooltips.

**Comment by Exuviax** [comment]
Hey Sephiroth,

The tooltip that you are seeing is actually something that is coming from Vanilla beam and not through us, the only users that you will see a tooltip on (Provided by our CSS) will appear over Developers names. Although I have reported the issue to Beam itself.

Thank you,
Exu

**Comment by SephirothWS** [comment]
No. This is an issue caused by the modifications to Vanilla Beam by Beam Extended.

**Comment by TATDK** [comment]
I'll take a look at it right away

**Comment by TATDK** [comment]
Fixed in f471160685772864ec01a9c73392505235eaa954
