### ISSUE TITLE
Beam updated their rank tooltip, BEx needs to be patched for this

### ISSUE THREAD

**Issue by MindlessPuppetz** [IFDevelopment/BeamExtended#41]
So, BEx causes the spacing and colors from ranks in the tooltip when hovering over a user to be gone ( http://t.co/oB5wYFJecU ) This does not happen when BEx is not installed/activated.

*flails about like a fish out of water til it is fixed*

**Comment by TATDK** [comment]
The reason behind this is because Beam changed the way roles are shown.
Working on a patch now.

**Comment by MindlessPuppetz** [comment]
*continues to flail about*

**Comment by Exuviax** [comment]
Beam CanYouNot
